const data = {
  login: 'Sayvai',
  id: 1234567,
  avatar_url: 'https://avatars0.githubusercontent.com/u/7581546?v=3',
  gravatar_id: '',
  url: 'https://api.github.com/users/Sayvai',
  html_url: 'https://github.com/Sayvai',
  followers_url: 'https://api.github.com/users/Sayvai/followers',
  following_url: 'https://api.github.com/users/Sayvai/following{/other_user}',
  gists_url: 'https://api.github.com/users/Sayvai/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Sayvai/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Sayvai/subscriptions',
  organizations_url: 'https://api.github.com/users/Sayvai/orgs',
  repos_url: 'https://api.github.com/users/Sayvai/repos',
  events_url: 'https://api.github.com/users/Sayvai/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Sayvai/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: null,
  location: null,
  email: null,
  hireable: null,
  bio: null,
  public_repos: 3,
  public_gists: 2,
  followers: 1,
  following: 1,
  created_at: '2014-05-14T13:30:41Z',
  updated_at: '2017-04-25T07:56:38Z',
};

export default data;
